name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/checkout@v3
      - name: set up java
        run: |
          sudo apt-get install curl
          sudo apt-get install tar
          curl -O https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.tar.gz
          tar -zxvf ./jdk-19_linux-x64_bin.tar.gz -C ./jdk19/
        env:
          JAVA_HOME: /usr/local/jdk-19.0.1/
          PATH: $JAVA_HOME/bin:$PATH
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kakabot:latest

      - name: download image
        uses: appleboy/ssh-action@v0.1.4
        with:
          key: ${{ secrets.SERVER_ACCESS_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          script_stop: true
          script: |
            sudo docker pull kakabot:latest
            sudo docker run -d --network host --name kakabot kakabot:latest
