name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/checkout@v3
      - name: download curl
        run:  docker pull xunop/xun_java19
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kakabot:latest

      - name: download image
        uses: appleboy/ssh-action@v0.1.4
        with:
          key: ${{ secrets.SERVER_ACCESS_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          script_stop: true
          script: |
            sudo docker pull kakabot:latest
            sudo docker run -d --network host --name kakabot kakabot:latest
