# This is a basic workflow to help you get started with Actions

name: kaBot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Rename target
      run: |
        mv target/*.jar target/kaBot.jar
        
        
    - name: Upload to server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        ARGS: '-avz --delete'
        SOURCE: 'target/ReviewSystem.jar'
        TARGET: '/home/ubuntu/botDocker'
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ubuntu
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_ACCESS_KEY }}
    
    - name: Restart Docker
      uses: appleboy/ssh-action@v0.1.4
      with:
        key: ${{ secrets.SERVER_ACCESS_KEY }}
        host: ${{ secrets.SERVER_HOST }}
        username: ubuntu
        script_stop: true
        script: |
          sudo docker restart BotContainer
